name: trackerbad
description: Application TrackerBadminton
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Graphiques
  fl_chart: ^0.69.0

  # Base de données SQLite + Drift (version moderne)
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.2

  # Utilitaires
  uuid: ^4.4.0
  shared_preferences: ^2.2.2

  # UI
  flutter_material_color_picker: ^1.1.0

dev_dependencies:
  drift_dev: ^2.15.0
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
